// This file is autogenerated by CMake: DO NOT EDIT

#ifdef HAVE_CONFIG_H
 #include "config.h"
#endif

#include "gpgme_backend_debug.h"


#if QT_VERSION >= QT_VERSION_CHECK(5, 4, 0)
Q_LOGGING_CATEGORY(GPGPME_BACKEND_LOG, "log_gpgme_backend", QtWarningMsg)
#else
Q_LOGGING_CATEGORY(GPGPME_BACKEND_LOG, "log_gpgme_backend")
#endif
