// This file is autogenerated by CMake: DO NOT EDIT

#ifdef HAVE_CONFIG_H
 #include "config.h"
#endif

#include "qgpgme_debug.h"


#if QT_VERSION >= QT_VERSION_CHECK(5, 4, 0)
Q_LOGGING_CATEGORY(QGPGME_LOG, "gpg.qgpgme", QtWarningMsg)
#else
Q_LOGGING_CATEGORY(QGPGME_LOG, "gpg.qgpgme")
#endif
